language: node_js
node_js:
  - "16"
sudo: required
services:
  - docker
before_install: 
  - docker build -t  ahmdjerid/docker-react -f Dockerfile.dev .

script: 
  - docker run  ahmdjerid/docker-react  npm run test -- --coverage
  - set -e
